"use client";

import { Bot, MessageCircle, Send, X } from "lucide-react";
import { FormEvent, useState } from "react";

type Message = { role: "user" | "assistant"; content: string };
export function AiChatbot() {
  const [open, setOpen] = useState(false); const [input, setInput] = useState(""); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "Hi. I can tell you about Md's experience, AI evaluation work, projects and skills. What would you like to know please let me know?" }]);
  async function sendMessage(event: FormEvent) { event.preventDefault(); const text = input.trim(); if (!text || loading) return; setInput(""); setMessages((items) => [...items, { role: "user", content: text }]); setLoading(true); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: text }) }); const data = await response.json(); setMessages((items) => [...items, { role: "assistant", content: data.reply || "I could not answer that right now." }]); } catch { setMessages((items) => [...items, { role: "assistant", content: "The assistant is temporarily unavailable. Please use the contact form instead." }]); } finally { setLoading(false); } }
  return <div className={`chatbot ${open ? "is-open" : ""}`}><button className="chat-toggle" type="button" onClick={() => setOpen((value) => !value)} aria-label={open ? "Close AI assistant" : "Open AI assistant"}>{open ? <X size={20} /> : <MessageCircle size={20} />}<span>Ask about Md</span></button>{open && <section className="chat-panel" aria-label="AI portfolio assistant"><div className="chat-heading"><span><Bot size={17} /> Portfolio assistant</span><small>AI guide</small></div><div className="chat-messages">{messages.map((message, index) => <p className={`chat-message ${message.role}`} key={`${message.role}-${index}`}>{message.content}</p>)}{loading && <p className="chat-message assistant">Thinking...</p>}</div><form className="chat-form" onSubmit={sendMessage}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about a project..." aria-label="Ask the portfolio assistant" /><button type="submit" aria-label="Send question"><Send size={16} /></button></form></section>}</div>;
}
